/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1001478_6.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1001478_1[] = { "Caminhão", "Mar", "Parado", "Sendo Erguido" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1001478_2_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1001478_2_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1001478_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1001478_2[39] = { 1.7572216088951067, -0.2522294811050477, 2.968698981791199, 1.4809776002861266, 1.4309762169637834, -0.5241052039337524, -0.6819898591730366, -0.9792347821972466, -1.2926837918300405, -1.4888596431449572, -1.6914454531368046, -1.7096015594299019, -1.6925722172482875, 1.2105964196896022, -0.16537455138137566, 3.965509823247367, 1.5065842279123132, 1.70342736234927, -0.4338868039915161, -0.6737949068845571, -0.8718250710984682, -1.1108667273240695, -1.2815989611134575, -1.4490313136756834, -1.495121444721068, -1.447821534977159, 2.1148993812441654, -0.4891989864619302, 3.8591188869015642, 1.338659075144717, 1.2758372161262355, -0.9689900695145521, -1.1360160433549886, -1.4370358164053927, -1.672758612412994, -1.792804162101878, -1.9571532151328235, -1.9502256292990539, -1.9108270246238597 };
const float ei_dn_standard_scaler_scale_1001478_2[39] = { 0.3501394861089255, 0.5840991270284478, 0.07729471482213963, 1.1515749519295415, 0.5325109979496455, 0.2923890599259646, 0.29517435231834954, 0.2994486829565771, 0.29599234450228373, 0.30346832823832337, 0.29073795496722826, 0.3023731876027426, 0.3016138618092623, 0.516394999801877, 0.5049050571462171, 0.05353458722647838, 1.017501440919391, 0.5043703758672587, 0.44835283132911485, 0.48288308643161737, 0.4956074757574372, 0.4863835503164019, 0.4960599180448228, 0.4803165180189449, 0.5004944343946439, 0.5012874848185268, 0.2658611676803857, 0.5275507097133274, 0.051710597599904276, 1.022405927905435, 0.5228408252155471, 0.2845136353797432, 0.2873613551214939, 0.2900613847932682, 0.2888818504596224, 0.29634704223244934, 0.28141947277663054, 0.29445528048665487, 0.29649321067051243 };
const float ei_dn_standard_scaler_var_1001478_2[39] = { 8.156762553061252, 2.931074692392601, 167.378781381579, 0.7540768012794424, 3.5264914613115677, 11.697088130818482, 11.477380034356187, 11.152062261352157, 11.414030865854413, 10.858585506280152, 11.830321233866187, 10.937383584073277, 10.992523567110933, 3.750040371710528, 3.922659023103901, 348.9241933233524, 0.9658950361132556, 3.930980225745277, 4.974622922238613, 4.288604649110876, 4.0712174812682935, 4.227097284345619, 4.063794382289127, 4.334559367403573, 3.992100768570961, 3.9794795362316195, 14.147841452548786, 3.5931188011219484, 373.9735495434134, 0.9566504547373054, 3.6581458528462165, 12.35360839444615, 12.109975763905451, 11.885574208976834, 11.98283240810854, 11.386724313599311, 12.626753721229393, 11.53350494287529, 11.375499979377071 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1001478_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1001478_2,
    .mean_data_len = 39,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1001478_2,
    .scale_data_len = 39,
    .var_data = (float *)ei_dn_standard_scaler_var_1001478_2,
    .var_data_len = 39
};
ei_data_normalization_t ei_data_normalization_config_1001478_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1001478_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1001478_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1001478_1[ei_dsp_blocks_1001478_1_size] = {
    { // DSP block 2
        2,
        39, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1001478_2, // pointer to config struct
        ei_dsp_config_1001478_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1001478_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1001478_2, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_1001478_6 = {
    .implementation_version = 1,
    .model = tflite_learn_1001478_6,
    .model_size = tflite_learn_1001478_6_len,
    .arena_size = tflite_learn_1001478_6_arena_size
};

const uint8_t ei_output_tensors_indices_1001478_6[1] = { 0 };
const uint8_t ei_output_tensors_size_1001478_6 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1001478_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .output_tensors_indices = ei_output_tensors_indices_1001478_6,
    .output_tensors_size = ei_output_tensors_size_1001478_6,
    .quantized = 1,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_1001478_6,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1001478_1_size = 1;
const uint32_t ei_learning_block_1001478_6_inputs[1] = { 2 };
const uint8_t ei_learning_block_1001478_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1001478_1[ei_learning_blocks_1001478_1_size] = {
    {
        6,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1001478_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1001478_6_inputs,
        ei_learning_block_1001478_6_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1001478_6 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1001478_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1001478_1[ei_postprocessing_blocks_1001478_1_size] = {
    {
        .block_id = 6,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1001478_6,
        .input_block_id = 6
    },
};

const uint8_t freeform_outputs_1001478_1_size = 0;

uint32_t *freeform_outputs_1001478_1 = nullptr;

const ei_impulse_t impulse_1001478_1 = {
    .project_id = 1001478,
    .project_owner = "EduCR03",
    .project_name = "Aula2-Classificacao_Movimento",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 39,
    .raw_sample_count = 125,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 125 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 16,
    .frequency = 62.5,

    .dsp_blocks_size = ei_dsp_blocks_1001478_1_size,
    .dsp_blocks = ei_dsp_blocks_1001478_1,

    .learning_blocks_size = ei_learning_blocks_1001478_1_size,
    .learning_blocks = ei_learning_blocks_1001478_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1001478_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1001478_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_ACCELEROMETER,
    .fusion_string = "accX + accY + accZ",
    .slice_size = (125/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1001478_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1001478_1_size,
    .freeform_outputs = freeform_outputs_1001478_1
};

ei_impulse_handle_t impulse_handle_1001478_1 = ei_impulse_handle_t( &impulse_1001478_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1001478_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1001478_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1001478_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1001478_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
